Allow license rules to require the presence of certain defining keywords
softsense/scancode-toolkit pull request #1
Opened 2021-11-09 09:45 UTC by mrombout

2021-11-11 14:00 UTC, petergardfjall reviewed
Very nicely done! :clap: 
Nice to see that the contribution turned out so managable in size!

Since I haven't dug down as deeply as you in the code, I have a bit of a hard time groking the intricacies of filtering and tokenizing/indexing, but I've challenged you to look more closely at it by asking some questions at least. :smile:

2021-11-11 14:41 UTC, mrombout commented on src/licensedcode/match.py
> +                key_phrase_span in match.ispan for key_phrase_span in match.rule.key_phrase_spans)):
* No the rule would not fire in that case, the order and positions must match.
* At `index_tokenizer#90` in `models.py` all `STOPWORDS` (see `stopwords.py`) are filtered out. But the words `in` and `the` are not part of that list.
* Key phrase words yes, but there can be multiple. There can be zero or more key phrase sequences, and each key phrase sequence may contain one or more words (tokens) which must be neighboring. So the following is valid to require `MIT` and `MIT-compatible license` to be present in the match.

  ```
  License 
  Distributed under the [[MIT]] License. See LICENSE for more information.
  You can redistribute this file under this or any [[MIT-compatible license]].
  ```

2021-11-11 14:42 UTC, petergardfjall commented on src/licensedcode/match.py
> +                key_phrase_span in match.ispan for key_phrase_span in match.rule.key_phrase_spans)):
Ok, good, just wanted to confirm the behavior. Maybe verify with a few simple test cases though (as suggested in a comment further down). I didn't seem to see many tests yet?

2021-11-11 14:42 UTC, mrombout commented on src/licensedcode/match.py
> +    matches, discarded = filter_key_phrase_spans(matches)
Non of the filter have an in-line comment, instead their behavior is document in their respective docstrings. At the moment I've put the following, based on the docstrings of the other filter methods.

```
    """
    Return a filtered list of kept LicenseMatch matches and a list of
    discardable matches by removing all matches that do not contain all key
    phrases required by the rule.
    """
```

2021-11-11 14:43 UTC, petergardfjall commented on src/licensedcode/match.py
> +    matches, discarded = filter_key_phrase_spans(matches)
ok, yeah I suppose that one should follow the conventions in the code base.

2021-11-11 15:07 UTC, petergardfjall commented on src/licensedcode/models.py
> +key_phrases_regex = re.compile(key_phrases_pattern, re.UNICODE)
Not really. Sounds like you've thought of it already.

2021-11-11 15:18 UTC, mrombout commented on tests/licensedcode/test_match.py
> +    def test_LicenseMatch_matches_only_when_all_key_phrases_are_present(self):
Good suggestion, one of the main struggles right now is to understand the meaning of `qspan` and `ispan` and how they are different between the different matching algorithms, and how to influence them. At the moment `1-hash` and `3-seq` matches do not behave as expect, but that hadn't been a problem in the rules I've been fixing, but I should look into it.

I'll mark this down as a TODO for now.

2021-11-11 15:21 UTC, mrombout commented on src/licensedcode/models.py
> +        required_span_index_sets = [[] for m in range(len(matches))]
b03d8bbb99fa08a088c95d4dcbd0f806fa67c394

2021-11-11 15:22 UTC, mrombout commented on src/licensedcode/models.py
> +            required_span_token_sets.append(required_tokens)
abcae1857f4173764a0ef6dd1308e68080f84edb

2021-11-11 15:24 UTC, mrombout commented on src/licensedcode/models.py
> +        be present in for this rule to be a valid match.
b03d8bbb99fa08a088c95d4dcbd0f806fa67c394

2021-11-11 15:28 UTC, mrombout commented on src/licensedcode/match.py
> +                key_phrase_span in match.ispan for key_phrase_span in match.rule.key_phrase_spans)):
Considering the intricacies of scanning algorithm(s), I went with testing from the outside-in, each `.txt` and `.yml` combo in `lic1` is a datadriven test that runs scancode and asserts on the licenses.

But unit-tests are coming soon.

2021-11-12 18:13 UTC, mrombout commented on src/licensedcode/data/rules/cddl-1.0_27.RULE
> +<name>[[CDDL 1]]</name>
Agreed, I originally changed because I saw `{` and `}` (single character) being used in the rules and figured that might conflict. But I've changed it to `{{` and `}}` and the datadriven tests still seem to work.

2021-11-12 18:13 UTC, mrombout commented on src/licensedcode/data/rules/cddl-1.0_27.RULE
> +<name>[[CDDL 1]]</name>
651315abf9dc2a9f9143ea06604197ffd45b35b9

2021-11-12 18:16 UTC, mrombout commented on src/licensedcode/index.py
> +            rule.key_phrase_spans = list(rule.key_phrases())
1fdba2390d92e70f63bdbdaab46b2d32cbaa0f64

2021-11-12 18:16 UTC, mrombout commented on src/licensedcode/index.py
> +            rule.key_phrase_spans = list(rule.key_phrases())
1fdba2390d92e70f63bdbdaab46b2d32cbaa0f64

2021-11-12 18:18 UTC, mrombout commented on src/licensedcode/models.py
> +key_phrases_pattern = '\\[\\[[\\w\\s]*\\]\\]'
Looks better, is there any compatibility issues with older Python versions maybe? Because `query_pattern` in `tokenize.py` also doesn't do that (which is what I was influenced by).

I can check later what happens if I change it.

2021-11-13 14:03 UTC, mrombout commented on tests/licensedcode/test_models.py
> +    def test_key_phrases_yields_nothing_when_unclosed_key_phrase_markup(self):
Not sure what the best way is to handle this. Personally I would prefer it to fail, because rules should always have correct syntax.

* Fail when we reach EOF while we're still appending key phrases.
* Considering everything after the opening bracket as a key phrase.

2021-11-19 13:40 UTC, mrombout commented on src/licensedcode/match.py
> +                    break
Do we want to break here? Since `ispan` is the index span wouldn't it always start at zero and thus the `if ipos in key_phrase_span` will also be `False` unless the key phrases are at the start of the rule?

2021-11-19 18:03 UTC, pombredanne commented on src/licensedcode/match.py
> +                    break
The idea was to say: if we have index-side position that is not in a key phrase........ hum...  ok, I get it. My logic was flawed, the `else` there may be superfluous and incorrect, the whole block from 1422 to 1424 might need to go

2021-11-22 13:55 UTC, pombredanne requested changes

2021-11-22 13:55 UTC, pombredanne commented on src/licensedcode/models.py
> +    key_phrase_spans = attr.ib(default=[], repr=False)
You cannot use a list instance as a default, that's a global with improbable behaviour. Instead use `attr.Factory(list)` which will lazily construct a new default instance for each new object.
 ```suggestion
    key_phrase_spans = attr.ib(default=attr.Factory(list), repr=False)
```

2021-11-22 14:03 UTC, pombredanne commented on src/licensedcode/tokenize.py
> +def key_phrase_tokenizer(text, stopwords=STOPWORDS):
A docstring and a battery of unit tests would be much welcomed IMHO for this important function

2021-11-22 16:22 UTC, mrombout commented on src/licensedcode/tokenize.py
> +def key_phrase_tokenizer(text, stopwords=STOPWORDS):
dd4e1e0c52469882d8b079aa259aabbf71453dbc

2021-11-22 16:22 UTC, mrombout commented on src/licensedcode/models.py
> +    def key_phrases(self):
7715dfaf5ea84cb1ed21261892a86972dea467fd

2021-11-25 13:02 UTC, pombredanne commented
@mrombout just a friendly reminder that you will need to amend your commit messages with a DCO signoff.

2021-11-25 13:15 UTC, pombredanne commented
@mrombout I pushed https://github.com/nexB/scancode-toolkit/pull/2765/commits/97a1a57eec13566328c26e67df6af1bb409144a9 in https://github.com/nexB/scancode-toolkit/pull/2765 wrt. unknowns_by_pos
I am not authorized to push to your softsense fork.

2021-11-28 17:21 UTC, mrombout commented on tests/licensedcode/test_models.py
> +    def test_key_phrases_yields_nothing_when_unclosed_key_phrase_markup(self):
For now it just ignores it, and does not consider it a key phrase.

2021-11-28 17:23 UTC, mrombout commented on src/licensedcode/match.py
> +                    break
Removed

2021-11-29 07:50 UTC, pombredanne commented on tests/licensedcode/test_models.py
> +    def test_get_key_phrases_yields_nothing_when_unclosed_key_phrase_markup(self):
IMHO we should fail loudly if there is any key phrase markup that is incomplete and not well balanced. The principle here would be to always ensure that the rule and license data is correct and that any incorrect data should fail tests.

2021-11-29 09:19 UTC, pombredanne commented on tests/licensedcode/test_match.py
> +from licensedcode.match import filter_contained_matches, filter_key_phrase_spans
Do you mind to have one import per line?

2021-11-29 09:20 UTC, pombredanne commented on tests/licensedcode/test_models.py
> +from licensedcode.models import Rule, get_key_phrases
nit: One import per line

2021-11-29 09:22 UTC, pombredanne commented on tests/licensedcode/test_models.py
> +
nit: this empty line and the one below may not be needed as I do not feel they help with readability?
(and the same applies to the test method here)

2021-11-29 09:23 UTC, pombredanne commented on tests/licensedcode/test_tokenize.py
> +from licensedcode.tokenize import index_tokenizer, key_phrase_tokenizer
nit: one import per line

2021-11-29 09:24 UTC, pombredanne reviewed
Except for the loud failing if there are invalid `{{key phrases}}` and a few optional nit pickings, this is looking great and all ready to merge IMHO!

2021-11-29 13:57 UTC, mrombout commented on tests/licensedcode/test_models.py
> +    def test_get_key_phrases_yields_nothing_when_unclosed_key_phrase_markup(self):
I've updated the code to do so and I am not running the test suite and found that some issues will not pass when being so strict. For example `src/licensedcode/data/rules/lgpl-3.0-plus_27.RULE` contains the following:

```
GNU Lesser General Public License, Version 3 {{{ */

 is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

 is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public License
along with .  If not, see <http://www.gnu.org/licenses/>.
```

Ways to work around it:

* Remove `{{{` from the rule, it wouldn't have any effect because it would be filtered out anyway?
* Come up with an alternative syntax that doesn't conflict.
  * Likely to become a problem in the future again, unless choosing something odd enough.
* Mark rule as having key phrases, but this feels cumbersome.

2021-11-29 14:40 UTC, pombredanne commented on tests/licensedcode/test_match.py
> +        assert len(matches) == 0
The `LicenseMatch,ispan` is the set of matched positions in a rule. All words of a rule are always known by constructions. If you zip the qspan and ispan, you would align the matched positions from each side. Different gaps may exist on each side in particular because of unknown words in the query do that do not exist at all in the single indexed rule. ... which is a common occurence when running a small made up index like this.
When using the full index, this would not be a different context. 

If I run these in the develop branch (not your branch) I get:
```
class TestIndexMatch(FileBasedTesting):

    def test_LicenseMatch_test(self):
        text_r1 = (
            'under the {{Creative Commons Attribution 4.0 International License}} (the "License");'
            'you may not use this file except in compliance with the License.'
            'You may obtain a copy of the License at'
            ''
            '     http://creativecommons.org/licenses/by/4.0'
            ''
            'This file is distributed on an "AS IS" BASIS,'
            'WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
            'See the License for the specific language governing permissions and'
            'limitations under the License.'
        )
        r1 = Rule(text_file='r1', license_expression='mit', stored_text=text_r1)
        idx = index.LicenseIndex([r1])

        querys = """
``.. Copyright 2010-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0
   International License (the "License"). You may not use this file except in compliance with the
   License. A copy of the License is located at http://creativecommons.org/licenses/by-nc-sa/4.0/.
   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
   either express or implied. See the License for the specific language governing permissions and
   limitations under the License.
        """

        matches = idx.match(query_string=querys, _skip_hash_match=True)
        assert len(matches) == 1
        match = matches[0]
        mqt, mit = get_texts(match)
        print()
        print(mqt)
        print()
        print("qpsan:", match.qspan)
        print()
        print(mit)
        print()
        print("ipsan:", match.ispan)

        raise Exception(mqt)

```
I get this output with pytest:
```
tests/licensedcode/test_keyphrase.py::TestIndexMatch::test_LicenseMatch_test 
Creative Commons Attribution-[NonCommercial]-[ShareAlike] 4.0 International
License (the "License"). You may not use this file except in compliance with the
License. A copy of the License [is] [located] at
http://creativecommons.org/licenses/by-[nc]-[sa]/4.[0]/. [This] file is
distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing
permissions [and] [limitations] under the License.

qspan: Span(6, 8)|Span(11, 32)|Span(34, 40)|Span(43, 70)|Span(72, 74)

creative commons attribution 4 0 international license the license you may not
use this file except in compliance with the license <you> <may> <obtain> copy of
the license at http creativecommons org licenses by 4 <0this> file is
distributed on an as is basis without warranties or conditions of any kind
either express or implied see the license for the specific language governing
permissions <andlimitations> under the license

ispan: Span(2, 22)|Span(26, 36)|Span(38, 65)|Span(67, 69)
```

this seems correct... there are unknown words.
And
```
class TestIndexMatch(FileBasedTesting):

    def test_LicenseMatch_test(self):
        text_r1 = (
            'under the {{Creative Commons Attribution 4.0 International License}} (the "License");'
            'you may not use this file except in compliance with the License.'
            'You may obtain a copy of the License at'
            ''
            '     http://creativecommons.org/licenses/by/4.0'
            ''
            'This file is distributed on an "AS IS" BASIS,'
            'WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.'
            'See the License for the specific language governing permissions and'
            'limitations under the License.'
        )
        r1 = Rule(text_file='r1', license_expression='mit', stored_text=text_r1)

        # this is a text containing words thatw ould be otherwise unknown
        text_r2 = """Commons Attribution NonCommercial ShareAlike
        This and limitations is located under nc-sa/4.0
        """

        r2 = Rule(text_file='r2', license_expression='bsd', stored_text=text_r2)

        idx = index.LicenseIndex([r1, r2])

        querys = """
``.. Copyright 2010-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0
   International License (the "License"). You may not use this file except in compliance with the
   License. A copy of the License is located at http://creativecommons.org/licenses/by-nc-sa/4.0/.
   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
   either express or implied. See the License for the specific language governing permissions and
   limitations under the License.
        """

        matches = idx.match(query_string=querys)#, _skip_hash_match=True)
        assert len(matches) == 1
        match = matches[0]
        mqt, mit = get_texts(match)
        print()
        print(mqt)
        print()
        print("qpsan:", match.qspan)
        print()
        print(mit)
        print()
        print("ipsan:", match.ispan)

        raise Exception(mqt)
```
will print:
```
Creative Commons Attribution-[NonCommercial]-[ShareAlike] 4.0 International
License (the "License"). You may not use this file except in compliance with the
License. A copy of the License [is] [located] at
http://creativecommons.org/licenses/by-[nc]-[sa]/[4].[0]/. [This] file is
distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the specific language governing
permissions [and] [limitations] under the License.

qspan: Span(6, 8)|Span(11, 32)|Span(35, 40)|Span(46, 73)|Span(76, 78)

creative commons attribution 4 0 international license the license you may not
use this file except in compliance with the license <you> <may> <obtain> copy of
the license at http creativecommons org licenses by <4> <0this> file is
distributed on an as is basis without warranties or conditions of any kind
either express or implied see the license for the specific language governing
permissions <andlimitations> under the license

ispan: Span(2, 22)|Span(26, 35)|Span(38, 65)|Span(67, 69)


```
which seems correct too.

2021-11-29 17:31 UTC, mrombout commented on src/licensedcode/data/rules/lgpl-3.0-plus_216.RULE
> -GNU Lesser General Public License, Version 3 {{{ */
NOTE: Just a temporary solution, do not merge

2021-11-29 17:31 UTC, mrombout commented on src/licensedcode/data/rules/lgpl-3.0-plus_27.RULE
> -GNU Lesser General Public License, Version 3 {{{ */
NOTE: Just a temporary solution, do not merge

2021-11-30 10:48 UTC, mrombout commented on tests/licensedcode/test_models.py
> +    def test_get_key_phrases_yields_nothing_when_unclosed_key_phrase_markup(self):
@petergardfjall Do you have an opinion on this?

2021-11-30 16:22 UTC, closed without merging